
trigger:
- master
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm run build'

- script: |
    dir
  displayName: 'list cwd contents (verify build)'

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/dist'
    azureSubscription: '1f85607e-cdfd-4c22-a61f-4602e22fcf4a'
    Destination: 'AzureBlob'
    storage: 'acc07'
    ContainerName: '$web'